apiVersion: v1
kind: ConfigMap
metadata:
  name: spinnaker-demo-config
  namespace: spinnah
data:
  NEW_FEATURE: "true"

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: spinnaker-demo
  namespace: spinnah
  labels:
    source: demo
    stack: frontend
    app: spinnaker
spec:
  replicas: 3
  selector:
    matchLabels:
      source: demo
      app: spinnaker
  template:
    metadata:
      labels:
        source: demo
        app: spinnaker
    spec:
      containers:
      - name: primary
        image: index.docker.io/kenoshi/spin-kub-v2-demo
        ports:
        - containerPort: 8001
        readinessProbe:
          httpGet:
            path: /
            port: 8001
        envFrom:
        - configMapRef:
            name: spinnaker-demo-config

---

kind: Service
apiVersion: v1
metadata:
  name: spinnaker-demo
  namespace: spinnah
spec:
  selector:
    source: demo
    app: spinnaker
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 10.70.0.0/16
  - 10.120.0.0/16
  - 96.78.187.189/29
  - 98.248.138.51/32
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8001
